apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}-deployment
spec:
  selector:
    matchLabels:
      app:  {{SERVICE_NAME}}-deployment
  template:
    metadata:
      labels:
        app:  {{SERVICE_NAME}}-deployment
    spec:
      containers:
      - name: {{SERVICE_NAME}}-deployment
        image: {{CASITA_IMAGE_NAME_TAG}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {{#if COMMAND}}
        command: ["{{{COMMAND}}}"]
        {{/if}}
        {{#if ARGS}}
        args: {{{json ARGS}}}
        {{/if}}
        env:
        - name: INSTANCE_ENV
          value: "{{BRANCH}}"
        - name: NFS_ROOT
          value: /storage/nfs
        {{#each env}}
        - name: {{name}}
          value: "{{value}}"
        {{/each}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
        - name: local-casita-tasks
          mountPath: /casita/tasks
          readOnly: true
        - name: local-casita-node-commons
          mountPath: /casita/node-commons
          readOnly: true
        - name: local-casita-services
          mountPath: /casita/services
          readOnly: true
      volumes:
      - name: local-casita-tasks
        hostPath:
          path: /hosthome/{{HOME_HOST_PATH}}/{{CASITA_TASKS_REPO_NAME}}/tasks
      - name: local-casita-node-commons
        hostPath:
          path: /hosthome/{{HOME_HOST_PATH}}/{{CASITA_TASKS_REPO_NAME}}/node-commons
      - name: local-casita-services
        hostPath:
          path: /hosthome/{{HOME_HOST_PATH}}/{{CASITA_TASKS_REPO_NAME}}/services
      - name: nfspsc
        persistentVolumeClaim:
          claimName: {{pvc-name}}
          readOnly: false
      {{#if nodeSelector}}
      nodeSelector:
        {{#if intendedfor}}
        intendedfor: krm-services
        {{/if}}
      {{/if}}
{{OK}}