version: '3'
services:

  zookeeper:
    image: {{ZOOKEEPER_IMAGE_NAME}}:{{ZOOKEEPER_TAG}}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog


  harvest:
    image: {{HARVEST_IMAGE_NAME}}:{{HARVEST_TAG}}
    env_file:
      - .env
    volumes:
       - harvest-xslt-data:/usr/local/vivo/harvester/data
       - harvest-data:/var/lib/harvest
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/lib:/usr/local/lib/harvest
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/ucdid:/usr/local/bin/ucdid
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/cdl:/usr/local/bin/cdl
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/harvest:/usr/local/bin/harvest
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/lib/node/lib:/service/lib
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/lib/node/index.js:/service/index.js
    command: tail -f /dev/null

  kafka:
    image: {{KAFKA_IMAGE_NAME}}:{{KAFKA_TAG}}
    env_file:
      - .env
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
      - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"
    ports:
      - 9092:9092

  redis:
    image: {{REDIS_IMAGE_NAME}}:{{REDIS_TAG}}
    volumes:
      - redis-data:/data

  composer:
    image: {{CASITA_COMPOSER_IMAGE_NAME}}:{{APP_VERSION}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/composer:/service/composer
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/expire:/service/expire
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/utils:/service/utils
      - ../casita-composer/lib:/casita/lib
    # command: bash -c "tail -f /dev/null"

  expire:
    image: {{A6T_IMAGE_NAME}}:{{A6T_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/composer:/service/composer
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/expire:/service/expire
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/utils:/service/utils
    command: node expire/instance.js
    # command: bash -c "tail -f /dev/null"

  decoder:
    image: {{CASITA_DECODER_IMAGE_NAME}}:{{APP_VERSION}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/composer:/service/composer
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/expire:/service/expire
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/utils:/service/utils
      - ../decoder/lib:/casita/lib
      - ../decoder/index.js:/casita/index.js
      - ./docker.key:/root/.ssh/id_rsa
    environment:
      - GRB_FILE=decoded
    restart: always
    # command: bash -c "tail -f /dev/null"


volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  redis-data: