version: '3'
services:

  zookeeper:
    image: {{ZOOKEEPER_IMAGE_NAME}}:{{ZOOKEEPER_TAG}}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: {{KAFKA_IMAGE_NAME}}:{{KAFKA_TAG}}
    env_file:
      - .env
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
      - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"
    ports:
      - 9092:9092

  redis:
    image: {{REDIS_IMAGE_NAME}}:{{REDIS_TAG}}
    volumes:
      - redis-data:/data

  composer:
    image: {{CASITA_A6T_IMAGE_NAME}}:{{APP_VERSION}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/composer:/service/composer
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/expire:/service/expire
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/utils:/service/utils
      - ../containers/casita-a6t/lib:/casita/lib
    command: node composer/instance.js
    # command: bash -c "tail -f /dev/null"

  expire:
    image: {{CASITA_A6T_IMAGE_NAME}}:{{APP_VERSION}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/composer:/service/composer
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/expire:/service/expire
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/utils:/service/utils
      - ../containers/casita-a6t/lib:/casita/lib
    command: node expire/instance.js
    # command: bash -c "tail -f /dev/null"

  init:
    image: {{CASITA_A6T_IMAGE_NAME}}:{{APP_VERSION}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/composer:/service/composer
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/expire:/service/expire
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/utils:/service/utils
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/init:/service/init
      - ../containers/casita-a6t/lib:/casita/lib
    command: node init
    # command: bash -c "tail -f /dev/null"

  decoder:
    image: {{CASITA_DECODER_IMAGE_NAME}}:{{APP_VERSION}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/composer:/service/composer
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/expire:/service/expire
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/utils:/service/utils
      - ../{{REPOSITORY_DIR}}/{{A6T_REPO_NAME}}/init:/service/init
      - ../containers/decoder/lib:/decoder/lib
      - ../containers/decoder/index.js:/decoder/index.js
      - ./docker.key:/root/.ssh/id_rsa
      - nfs-data:/storage
    environment:
      - GRB_FILE=decoded
    command: bash -c "tail -f /dev/null"


volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  redis-data:
  nfs-data: