apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{pv-name}}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{pv-size}}
  hostPath:
    path: /hosthome/{{HOME_HOST_PATH}}/minikube-data